name: Daily Dependency Release Check

on:
  schedule:
    - cron: '0 8 * * *' # Runs at 8 AM UTC every day
  workflow_dispatch: # Allows manual triggering

jobs:
  check_releases:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./website/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run release check script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx ts-node scripts/check-releases.ts 